### PR TITLE
P1 SSO Typo Fix

### PR DESCRIPTION
**Pull request by adl-trey**
Fixing a copy/paste issue that resulted in the token check comparing the wrong property, namely the `iss` instead of `azp`.

**Security Info:** None, this is just a correction.

### CODE REVIEW

**Comment by adl-trey** [comment]
Afternoon @Lomilar, I have a few updates for the P1 integration etc.

P1 handles the tokens and access, so I'm considering the issuer + client checks as safe enough -- as the issue time was causing problems for some reason.

**Comment by Lomilar** [comment]
Time always causes problems. It could be that P1 JWT is using unix epoch time in ms vs unix epoch time in seconds. (hence the * 1000).

Please note, you're removing the check that prevents replay attacks. May want to check with your STIGs.

Let me know and I'll go ahead.

**Comment by FlorianTolk** [comment]
Funnily enough, we are not actually responsible for handling the sign-On process.

This is for a CaSS instance that sits behind an instance of Istio, which is responsible for actually handling access to cass. Once a user is authorized by Istio, we are allowed to assume their token is valid.

**Comment by vbhayden** [comment]
instances using this approach aren't accessible unless their session has already been validated by the overarching proxy, so it should still be ok.  I'll update to only skip the time verification when the environment has specific that it's ok to do so.

**Comment by adl-trey** [comment]
Ok, should be fine now -- will be enforced unless the env allows it to be skipped etc.

**Comment by adl-trey** [comment]
Just updated with that, had originally followed the example above with the `CASS_JWT_ENABLED` env flag etc.

**Pull request merged**
